### ISSUE TITLE
Run Integration Tests in Eclipse

### ISSUE THREAD

**Issue by bagnier** [g00glen00b/ng-spring-boot#1]
Hi !

The integration tests execute from the Maven command line but not from Eclipse. In Eclipse, integration tests tell:

```
java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html
    at com.google.common.base.Preconditions.checkState(Preconditions.java:177)
    at org.openqa.selenium.phantomjs.PhantomJSDriverService.findPhantomJS(PhantomJSDriverService.java:237)
    at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:182)
    at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:99)
    at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:89)
    at be.g00glen00b.functional.ApplicationIT.<init>(ApplicationIT.java:43)
    ...
```

In Eclipse, the pom.xml file exhibits an error on the phantomjs-maven-plugin configuration:

```
Plugin execution not covered by lifecycle configuration: 
com.github.klieber:phantomjs-maven-plugin:0.4:install (execution: default, phase: process-test-sources)
```

Actually Eclipse does not execute the phantomjs-maven-plugin and cannot launch PhantomJS. Many ways to fix it, I choose to pass an environment variable to the Eclipse JUnit Runner and to setup correctly the PhantomJSDriver. Now this works in Maven and in Eclipse.

**Comment by g00glen00b** [comment]
That's indeed true, to run them in Eclipse you have to add a VM argument. I explained this as well in my article about the integration tests: http://g00glen00b.be/spring-boot-selenium/ (at the bottom of the article).
Normally you should be able to execute the integration tests through Maven as well when using Eclipse. Just make sure you add the process-test-sources phase to the list of known phases (Eclipse already suggests this as a quick fix). Also make sure that you're passing the `-Dprofile integration` VM argument.

Anyways, you can achieve both things by using Run Configurations in Eclipse.

**Comment by bagnier** [comment]
Oh yes, you're absolutely right !

Thank you for the tip !
